# Generated by Django 4.2.7 on 2026-02-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_vendor__69616a_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
    ]
